/**
 * Parser tests. Fixtures are generated by test/make-fixtures.sh using the
 * ffmpeg CLI, so they are real files written by a real muxer rather than
 * hand-rolled byte blobs.
 *
 *   node --test test/
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  readMetadata, sniff, readMp3, readFlac, readOgg, readMp4, readWav,
} from '../js/metadata.js';
import { estimateSize, buildArgs, FORMATS, defaultQuality } from '../js/formats.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, 'fixtures');

const load = (name) => new Uint8Array(readFileSync(join(FIXTURES, name)));
const have = (name) => existsSync(join(FIXTURES, name));

const EXPECTED = {
  title: 'Slow Tide',
  artist: 'Marion Vale',
  album: 'Harbour Lights',
  albumArtist: 'Marion Vale',
  track: '7',
  trackTotal: '12',
  year: '2019',
  genre: 'Ambient',
};

const CASES = [
  { file: 'mp3_320_art.mp3', container: 'mp3', cover: 'image/jpeg', duration: 3.5 },
  { file: 'mp3_v0.mp3', container: 'mp3', cover: null, duration: 3.5 },
  { file: 'flac_art.flac', container: 'flac', cover: 'image/png', duration: 3.5 },
  { file: 'aac_art.m4a', container: 'mp4', cover: 'image/jpeg', duration: 3.5 },
  { file: 'opus.opus', container: 'opus', cover: null, duration: 3.5 },
  { file: 'vorbis.ogg', container: 'vorbis', cover: null, duration: 3.5 },
  { file: 'wav_tagged.wav', container: 'wav', cover: null, duration: 3.5 },
];

for (const c of CASES) {
  test(`${c.file}: text tags`, { skip: !have(c.file) && 'fixture missing' }, () => {
    const t = readMetadata(load(c.file), c.file);
    assert.equal(t.container, c.container);
    assert.equal(t.title, EXPECTED.title);
    assert.equal(t.artist, EXPECTED.artist);
    assert.equal(t.album, EXPECTED.album);

    // WAV's INFO chunk has no album-artist or track-total field.
    if (c.container !== 'wav') {
      assert.equal(t.albumArtist, EXPECTED.albumArtist);
      assert.equal(t.trackTotal, EXPECTED.trackTotal);
    }
    assert.equal(t.track, EXPECTED.track);
    assert.equal(t.year, EXPECTED.year);
    assert.equal(t.genre, EXPECTED.genre);
  });

  test(`${c.file}: duration and stream shape`, { skip: !have(c.file) && 'fixture missing' }, () => {
    const t = readMetadata(load(c.file), c.file);
    assert.ok(
      Math.abs(t.duration - c.duration) < 0.15,
      `duration ${t.duration} should be near ${c.duration}`,
    );
    assert.equal(t.channels, 2);
    assert.ok(t.bitrate > 0, 'bitrate should be positive');
    if (c.container !== 'opus') assert.equal(t.sampleRate, 44100);
  });

  test(`${c.file}: cover art`, { skip: !have(c.file) && 'fixture missing' }, () => {
    const t = readMetadata(load(c.file), c.file);
    if (c.cover === null) {
      assert.equal(t.cover, null);
      return;
    }
    assert.ok(t.cover, 'expected embedded cover art');
    assert.equal(t.cover.mime, c.cover);
    assert.ok(t.cover.bytes.length > 100, 'cover should have real bytes');

    // Verify the extracted bytes are a valid image, not a mis-sliced buffer.
    const b = t.cover.bytes;
    if (c.cover === 'image/jpeg') {
      assert.equal(b[0], 0xff, 'JPEG SOI byte 1');
      assert.equal(b[1], 0xd8, 'JPEG SOI byte 2');
      assert.equal(b[b.length - 2], 0xff, 'JPEG EOI byte 1');
      assert.equal(b[b.length - 1], 0xd9, 'JPEG EOI byte 2');
    } else {
      assert.deepEqual([...b.slice(0, 4)], [0x89, 0x50, 0x4e, 0x47], 'PNG signature');
    }
  });
}

test('sniff identifies every fixture container', () => {
  const map = {
    'mp3_320_art.mp3': 'mp3', 'mp3_v0.mp3': 'mp3', 'flac_art.flac': 'flac',
    'aac_art.m4a': 'mp4', 'opus.opus': 'ogg', 'vorbis.ogg': 'ogg',
    'wav_tagged.wav': 'wav',
  };
  for (const [file, kind] of Object.entries(map)) {
    if (have(file)) assert.equal(sniff(load(file)), kind, file);
  }
});

test('non-latin text survives ID3 UTF-16 encoding', { skip: !have('utf.mp3') && 'fixture missing' }, () => {
  const t = readMetadata(load('utf.mp3'), 'utf.mp3');
  assert.equal(t.title, 'Låt № 3 — 東京');
  assert.equal(t.artist, 'Ø Ensemble');
});

test('320k CBR MP3 reports its real bitrate', { skip: !have('mp3_320_art.mp3') && 'fixture missing' }, () => {
  const t = readMp3(load('mp3_320_art.mp3'));
  assert.ok(t.bitrate >= 310000 && t.bitrate <= 330000, `got ${t.bitrate}`);
});

test('VBR MP3 uses the Xing frame count, not a CBR guess', { skip: !have('mp3_v0.mp3') && 'fixture missing' }, () => {
  const t = readMp3(load('mp3_v0.mp3'));
  assert.ok(Math.abs(t.duration - 3.5) < 0.1, `got ${t.duration}`);
});

test('untagged input falls back to the filename as title', () => {
  const bytes = load('src.wav');
  const t = readMetadata(bytes, 'Some Untitled Take.wav');
  assert.equal(t.title, 'Some Untitled Take');
  assert.equal(t.titleFromFilename, true);
});

test('garbage input returns a usable empty track rather than throwing', () => {
  const junk = new Uint8Array(4096).fill(0x5a);
  const t = readMetadata(junk, 'junk.bin');
  assert.equal(t.title, 'junk');
  assert.equal(t.cover, null);
  assert.equal(t.duration, 0);
});

test('truncated file does not throw', () => {
  const bytes = load('flac_art.flac').slice(0, 900);
  assert.doesNotThrow(() => readMetadata(bytes, 'cut.flac'));
});

// ---------------------------------------------------------------- estimation

test('size estimate for lossy output tracks the bitrate', () => {
  const track = { duration: 300, sampleRate: 44100, channels: 2 };
  const opus160 = estimateSize('opus', '160', track);
  assert.ok(Math.abs(opus160 - 6_000_000) < 200_000, `got ${opus160}`);

  // Doubling the bitrate should roughly double the file.
  const opus96 = estimateSize('opus', '96', track);
  assert.ok(opus160 / opus96 > 1.6 && opus160 / opus96 < 1.75);
});

test('WAV estimate matches the exact PCM arithmetic', () => {
  const track = { duration: 60, sampleRate: 44100, channels: 2 };
  assert.equal(estimateSize('wav', '16', track), 60 * 44100 * 2 * 2 + 44);
});

test('estimate returns null when duration is unknown', () => {
  assert.equal(estimateSize('opus', '160', { duration: 0 }), null);
});

test('every format has a suggested quality that resolves', () => {
  for (const id of Object.keys(FORMATS)) {
    const q = defaultQuality(id);
    assert.ok(FORMATS[id].qualities.some((x) => x.id === q), id);
  }
});

// ---------------------------------------------------------------- ffmpeg args

test('opus command drops cover art and asks for VBR', () => {
  const args = buildArgs({
    inputName: 'in.mp3', outputName: 'out.opus', formatId: 'opus',
    qualityId: '160', coverName: 'cover.jpg', tags: {},
  });
  const line = args.join(' ');
  assert.ok(line.includes('-c:a libopus'));
  assert.ok(line.includes('-b:a 160k'));
  assert.ok(line.includes('-vbr on'));
  assert.ok(!line.includes('cover.jpg'), 'Opus output must not try to mux a picture');
  assert.ok(line.includes('-map 0:a:0'));
});

test('mp3 command muxes cover art with the front-cover disposition', () => {
  const args = buildArgs({
    inputName: 'in.flac', outputName: 'out.mp3', formatId: 'mp3',
    qualityId: 'v2', coverName: 'cover.jpg', tags: {},
  });
  const line = args.join(' ');
  assert.ok(line.includes('-i cover.jpg'));
  assert.ok(line.includes('-map 1:v:0'));
  assert.ok(line.includes('attached_pic'));
  assert.ok(line.includes('-q:a 2'), 'V2 should map to -q:a 2');
  assert.ok(line.includes('Cover (front)'));
});

test('user tag edits are appended as -metadata', () => {
  const args = buildArgs({
    inputName: 'in.mp3', outputName: 'out.m4a', formatId: 'm4a',
    qualityId: '192', coverName: null,
    tags: { title: 'New Name', artist: '', album: 'Kept' },
  });
  const line = args.join(' ');
  assert.ok(line.includes('-metadata title=New Name'));
  assert.ok(line.includes('-metadata album=Kept'));
  assert.ok(!line.includes('artist='), 'blank values should be skipped entirely');
});

test('output filename is always the final argument', () => {
  for (const id of Object.keys(FORMATS)) {
    const args = buildArgs({
      inputName: 'in.wav', outputName: `out.${FORMATS[id].ext}`, formatId: id,
      qualityId: defaultQuality(id), coverName: 'c.jpg', tags: {},
    });
    assert.equal(args[args.length - 1], `out.${FORMATS[id].ext}`, id);
    assert.equal(args[args.length - 2], '-y', id);
  }
});
